name: reed-catalog-dev
services:
  mysql-dev:
    container_name: mysql_dev
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reed_catalog
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3307:3306"
    networks:
      - reed_catalog_dev_network

  reed-catalog-app-dev:
    container_name: reed_catalog_app_dev
    depends_on:
      mysql-dev:
        condition: service_healthy
        restart: true
    env_file:
      - .env.dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_dev:3306/reed_catalog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    networks:
      - reed_catalog_dev_network

networks:
  reed_catalog_dev_network:
    name: reed_catalog_dev_network