name: Java CI with gradle
on:
  push:
    branches: [ main, dev, ci-cd/ci ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar
          ./gradlew build

      - name: Run tests
        run: ./gradlew test